### ISSUE TITLE
Prestashop 8.0.3

### ISSUE THREAD

**Issue by ikrami2000** [paytabscom/paytabs-prestashop#21]
I have Prestashop 8.0.3  and I contact your agent and my bank activate the account. Now when i try to upload the Module it is return Error: Installation of module failed. This file does not seem to be a valid module zip

**Comment by wajihkm** [comment]
Hi,

Kindly make sure you downloaded the correct zip format.
The latest version:
https://github.com/paytabscom/paytabs-prestashop/releases/download/3.7.0/paytabs_paypage.zip

You can find it in the ReadMe file, or as an Asset in the Release.
https://github.com/paytabscom/paytabs-prestashop/releases/tag/3.7.0

Regards,
