### ISSUE TITLE
i have a problem 

### ISSUE THREAD

**Issue by amirmohamed87** [paytabscom/paytabs-prestashop#4]
after i uploaded the zip file , an error appeared 
[PrestaShop] Fatal error in module file :/home/wevent360/public_html/modules/paytabs_paypage/paytabs_paypage.php:
Cannot redeclare paytabs_error_log() (previously declared in /home/wevent360/public_html/modules/paytabs/paytabs.php:34)

and i can not enter the modules page >> it just appear that error in the page 

what can i do plz?

**Comment by wajihkm** [comment]
Hi @amirmohamed87 ,

You must delete the previous paytabs plugin,
Kindly navigate to the folder: `/home/wevent360/public_html/modules` then delete the folder `paytabs`.

Regards
